/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anther;

/**
 *
 * @author PCUNO
 */
public class estudiantes extends javax.swing.JFrame {

    /**
     * Creates new form estudiantes
     */
    public estudiantes() {
        this.setLocation((1080/2), 50);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        n1TXT = new javax.swing.JTextField();
        n2TXT = new javax.swing.JTextField();
        calcBTN = new javax.swing.JButton();
        n3TXT = new javax.swing.JTextField();
        rLBL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salirBTN = new javax.swing.JButton();
        borrarBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nota Final");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        n1TXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n1TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 200, 34));

        n2TXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n2TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, 34));

        calcBTN.setText("Calcular");
        calcBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBTNActionPerformed(evt);
            }
        });
        getContentPane().add(calcBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 360, 34));

        n3TXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n3TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 200, 34));

        rLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rLBL.setForeground(new java.awt.Color(255, 255, 255));
        rLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(rLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 200, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nota 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nota 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nota 3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 150, 34));

        salirBTN.setText("Salir");
        salirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBTNActionPerformed(evt);
            }
        });
        getContentPane().add(salirBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 170, 34));

        borrarBTN.setText("Borrar");
        borrarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(borrarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 170, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blackboard.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBTNActionPerformed
        double a = Double.parseDouble(this.n1TXT.getText());
        double b = Double.parseDouble(this.n2TXT.getText());
        double c = Double.parseDouble(this.n3TXT.getText());
        double d = (a * 0.55)+(b * 0.30)+(c * 0.15);
        this.rLBL.setText(String.valueOf(d));
    }//GEN-LAST:event_calcBTNActionPerformed

    private void borrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBTNActionPerformed
        this.n1TXT.setText("");
        this.n2TXT.setText("");
        this.n3TXT.setText("");
        this.rLBL.setText("");
    }//GEN-LAST:event_borrarBTNActionPerformed

    private void salirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBTN;
    private javax.swing.JButton calcBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField n1TXT;
    private javax.swing.JTextField n2TXT;
    private javax.swing.JTextField n3TXT;
    private javax.swing.JLabel rLBL;
    private javax.swing.JButton salirBTN;
    // End of variables declaration//GEN-END:variables
}
