/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anther;

import newp.menu;

/**
 *
 * @author casa
 */
public class hospital extends javax.swing.JFrame {

    /**
     * Creates new form hospital
     */
    public hospital() {
        this.setLocation((1080 / 2), 50);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presupuestoTXT = new javax.swing.JTextField();
        borrarBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        calcBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gineLBL = new javax.swing.JLabel();
        oncoLBL = new javax.swing.JLabel();
        pedLBL = new javax.swing.JLabel();
        ortLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(presupuestoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 380, 34));

        borrarBTN.setText("Borrar");
        borrarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(borrarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 120, 40));

        exitBTN.setText("Salir");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 120, 40));

        calcBTN.setText("Calcular");
        calcBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBTNActionPerformed(evt);
            }
        });
        getContentPane().add(calcBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Presupuesto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 380, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hospital");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Oncología");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 200, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pediatría");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 200, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ortopédica");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 200, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ginecología");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 34));

        gineLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gineLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(gineLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 200, 34));

        oncoLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oncoLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(oncoLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 200, 34));

        pedLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pedLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pedLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 200, 34));

        ortLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ortLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ortLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 200, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/working-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 684, 476));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBTNActionPerformed

    private void borrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBTNActionPerformed
        this.gineLBL.setText("");
        this.oncoLBL.setText("");
        this.ortLBL.setText("");
        this.pedLBL.setText("");
        this.presupuestoTXT.setText("");
    }//GEN-LAST:event_borrarBTNActionPerformed

    private void calcBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBTNActionPerformed
        double a, b, c, d;
        a = Double.parseDouble(this.presupuestoTXT.getText()) * 0.20;
        b = Double.parseDouble(this.presupuestoTXT.getText()) * 0.40;
        c = Double.parseDouble(this.presupuestoTXT.getText()) * 0.30;
        d = Double.parseDouble(this.presupuestoTXT.getText()) * 0.10;

        this.gineLBL.setText(String.valueOf(a));
        this.oncoLBL.setText(String.valueOf(b));
        this.pedLBL.setText(String.valueOf(c));
        this.ortLBL.setText(String.valueOf(d));
    }//GEN-LAST:event_calcBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBTN;
    private javax.swing.JButton calcBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel gineLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel oncoLBL;
    private javax.swing.JLabel ortLBL;
    private javax.swing.JLabel pedLBL;
    private javax.swing.JTextField presupuestoTXT;
    // End of variables declaration//GEN-END:variables
}
