/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anther;

import newp.menu;

/**
 *
 * @author casa
 */
public class pdf4 extends javax.swing.JFrame {

    /**
     * Creates new form pdf4
     */
    public pdf4() {
        this.setLocation((1080 / 2), (100));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        n2Txt = new javax.swing.JTextField();
        n1Txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opBox = new javax.swing.JComboBox<>();
        borrarBtn = new javax.swing.JButton();
        calcuBtn = new javax.swing.JButton();
        rLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        getContentPane().add(n2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 200, 35));
        getContentPane().add(n1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Operacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Numero 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 35));

        opBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Suma", "Resta", "Multiplicacion", "Division" }));
        opBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opBoxActionPerformed(evt);
            }
        });
        getContentPane().add(opBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, 35));

        borrarBtn.setText("Borrar");
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(borrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 340, 35));

        calcuBtn.setText("Calcular");
        calcuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcuBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calcuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 340, 35));

        rLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(rLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void opBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opBoxActionPerformed
        
    }//GEN-LAST:event_opBoxActionPerformed

    private void calcuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcuBtnActionPerformed
        double a = Double.parseDouble(this.n1Txt.getText());
        double b = Double.parseDouble(this.n2Txt.getText());
        String c = this.opBox.getSelectedItem().toString();
        double d;
        switch(c){
            case "Suma":
                d = a + b;
                this.rLbl.setText(String.valueOf(d));
                break;
            case "Resta":
                d = a - b;
                this.rLbl.setText(String.valueOf(d));
                break;
            case "Multiplicacion":
                d = a * b;
                this.rLbl.setText(String.valueOf(d));
                break;
            case "Division":
                d = a / b;
                this.rLbl.setText(String.valueOf(d));
                break;
            default:
                this.rLbl.setText("Seleccione una operacion");
                break;
        }
    }//GEN-LAST:event_calcuBtnActionPerformed

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        this.n1Txt.setText("");
        this.n2Txt.setText("");
        this.opBox.setSelectedIndex(0);
        this.rLbl.setText("");
    }//GEN-LAST:event_borrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pdf4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pdf4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pdf4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pdf4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pdf4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBtn;
    private javax.swing.JButton calcuBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField n1Txt;
    private javax.swing.JTextField n2Txt;
    private javax.swing.JComboBox<String> opBox;
    private javax.swing.JLabel rLbl;
    // End of variables declaration//GEN-END:variables
}
